#pragma checksum "..\..\..\..\UI\TextToCADTaskpaneWpf.xaml" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "3777939DD4A7DE29D78D9A6AB367CB6587322F13"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Diagnostics;
using System.Windows;
using System.Windows.Automation;
using System.Windows.Controls;
using System.Windows.Controls.Primitives;
using System.Windows.Controls.Ribbon;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Forms.Integration;
using System.Windows.Ink;
using System.Windows.Input;
using System.Windows.Markup;
using System.Windows.Media;
using System.Windows.Media.Animation;
using System.Windows.Media.Effects;
using System.Windows.Media.Imaging;
using System.Windows.Media.Media3D;
using System.Windows.Media.TextFormatting;
using System.Windows.Navigation;
using System.Windows.Shapes;
using System.Windows.Shell;


namespace AICAD.UI {
    
    
    /// <summary>
    /// TextToCADTaskpaneWpf
    /// </summary>
    public partial class TextToCADTaskpaneWpf : System.Windows.Controls.UserControl, System.Windows.Markup.IComponentConnector {
        
        
        #line 26 "..\..\..\..\UI\TextToCADTaskpaneWpf.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label presetLabel;
        
        #line default
        #line hidden
        
        
        #line 27 "..\..\..\..\UI\TextToCADTaskpaneWpf.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ComboBox shapePreset;
        
        #line default
        #line hidden
        
        
        #line 33 "..\..\..\..\UI\TextToCADTaskpaneWpf.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label lblVersion;
        
        #line default
        #line hidden
        
        
        #line 34 "..\..\..\..\UI\TextToCADTaskpaneWpf.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label lblModified;
        
        #line default
        #line hidden
        
        
        #line 38 "..\..\..\..\UI\TextToCADTaskpaneWpf.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label lblRealTimeStatus;
        
        #line default
        #line hidden
        
        
        #line 41 "..\..\..\..\UI\TextToCADTaskpaneWpf.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox prompt;
        
        #line default
        #line hidden
        
        
        #line 45 "..\..\..\..\UI\TextToCADTaskpaneWpf.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button build;
        
        #line default
        #line hidden
        
        
        #line 49 "..\..\..\..\UI\TextToCADTaskpaneWpf.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button btnThumbDown;
        
        #line default
        #line hidden
        
        
        #line 50 "..\..\..\..\UI\TextToCADTaskpaneWpf.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button btnThumbUp;
        
        #line default
        #line hidden
        
        
        #line 55 "..\..\..\..\UI\TextToCADTaskpaneWpf.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button btnHistory;
        
        #line default
        #line hidden
        
        
        #line 56 "..\..\..\..\UI\TextToCADTaskpaneWpf.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button btnStatus;
        
        #line default
        #line hidden
        
        
        #line 57 "..\..\..\..\UI\TextToCADTaskpaneWpf.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button btnSettings;
        
        #line default
        #line hidden
        
        private bool _contentLoaded;
        
        /// <summary>
        /// InitializeComponent
        /// </summary>
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "9.0.11.0")]
        public void InitializeComponent() {
            if (_contentLoaded) {
                return;
            }
            _contentLoaded = true;
            System.Uri resourceLocater = new System.Uri("/AI-CAD-December;V1.0.0.0;component/ui/texttocadtaskpanewpf.xaml", System.UriKind.Relative);
            
            #line 1 "..\..\..\..\UI\TextToCADTaskpaneWpf.xaml"
            System.Windows.Application.LoadComponent(this, resourceLocater);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "9.0.11.0")]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
        void System.Windows.Markup.IComponentConnector.Connect(int connectionId, object target) {
            switch (connectionId)
            {
            case 1:
            this.presetLabel = ((System.Windows.Controls.Label)(target));
            return;
            case 2:
            this.shapePreset = ((System.Windows.Controls.ComboBox)(target));
            return;
            case 3:
            this.lblVersion = ((System.Windows.Controls.Label)(target));
            return;
            case 4:
            this.lblModified = ((System.Windows.Controls.Label)(target));
            return;
            case 5:
            this.lblRealTimeStatus = ((System.Windows.Controls.Label)(target));
            return;
            case 6:
            this.prompt = ((System.Windows.Controls.TextBox)(target));
            return;
            case 7:
            this.build = ((System.Windows.Controls.Button)(target));
            return;
            case 8:
            this.btnThumbDown = ((System.Windows.Controls.Button)(target));
            return;
            case 9:
            this.btnThumbUp = ((System.Windows.Controls.Button)(target));
            return;
            case 10:
            this.btnHistory = ((System.Windows.Controls.Button)(target));
            return;
            case 11:
            this.btnStatus = ((System.Windows.Controls.Button)(target));
            return;
            case 12:
            this.btnSettings = ((System.Windows.Controls.Button)(target));
            return;
            }
            this._contentLoaded = true;
        }
    }
}

