<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net48</TargetFramework>
    <LangVersion>7.3</LangVersion>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="SolidWorks.Interop.sldworks">
      <HintPath>..\References\SolidWorks.Interop.sldworks.dll</HintPath>
      <Private>true</Private>
    </Reference>
    <Reference Include="SolidWorks.Interop.swconst">
      <HintPath>..\References\SolidWorks.Interop.swconst.dll</HintPath>
      <Private>true</Private>
    </Reference>
  </ItemGroup>
</Project>
