#pragma checksum "..\..\..\UI\TextToCADTaskpaneWpf.xaml" "{8829d00f-11b8-4213-878b-770e8597ac16}" "98EB0F52A9593A2D6CDA4989F487F115FCCB36250B7135871F4FDB84F2909234"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Diagnostics;
using System.Windows;
using System.Windows.Automation;
using System.Windows.Controls;
using System.Windows.Controls.Primitives;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Forms.Integration;
using System.Windows.Ink;
using System.Windows.Input;
using System.Windows.Markup;
using System.Windows.Media;
using System.Windows.Media.Animation;
using System.Windows.Media.Effects;
using System.Windows.Media.Imaging;
using System.Windows.Media.Media3D;
using System.Windows.Media.TextFormatting;
using System.Windows.Navigation;
using System.Windows.Shapes;
using System.Windows.Shell;


namespace AICAD.UI {
    
    
    /// <summary>
    /// TextToCADTaskpaneWpf
    /// </summary>
    public partial class TextToCADTaskpaneWpf : System.Windows.Controls.UserControl, System.Windows.Markup.IComponentConnector {
        
        
        #line 35 "..\..\..\UI\TextToCADTaskpaneWpf.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label presetLabel;
        
        #line default
        #line hidden
        
        
        #line 36 "..\..\..\UI\TextToCADTaskpaneWpf.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ComboBox shapePreset;
        
        #line default
        #line hidden
        
        
        #line 42 "..\..\..\UI\TextToCADTaskpaneWpf.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label lblVersion;
        
        #line default
        #line hidden
        
        
        #line 43 "..\..\..\UI\TextToCADTaskpaneWpf.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label lblModified;
        
        #line default
        #line hidden
        
        
        #line 47 "..\..\..\UI\TextToCADTaskpaneWpf.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox prompt;
        
        #line default
        #line hidden
        
        
        #line 50 "..\..\..\UI\TextToCADTaskpaneWpf.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button build;
        
        #line default
        #line hidden
        
        
        #line 53 "..\..\..\UI\TextToCADTaskpaneWpf.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label lblRealTimeStatus;
        
        #line default
        #line hidden
        
        
        #line 60 "..\..\..\UI\TextToCADTaskpaneWpf.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button btnThumbUp;
        
        #line default
        #line hidden
        
        
        #line 61 "..\..\..\UI\TextToCADTaskpaneWpf.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button btnThumbDown;
        
        #line default
        #line hidden
        
        
        #line 67 "..\..\..\UI\TextToCADTaskpaneWpf.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button btnHistory;
        
        #line default
        #line hidden
        
        
        #line 68 "..\..\..\UI\TextToCADTaskpaneWpf.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button btnStatus;
        
        #line default
        #line hidden
        
        
        #line 69 "..\..\..\UI\TextToCADTaskpaneWpf.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button btnSettings;
        
        #line default
        #line hidden
        
        private bool _contentLoaded;
        
        /// <summary>
        /// InitializeComponent
        /// </summary>
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        public void InitializeComponent() {
            if (_contentLoaded) {
                return;
            }
            _contentLoaded = true;
            System.Uri resourceLocater = new System.Uri("/AI-CAD-December;component/ui/texttocadtaskpanewpf.xaml", System.UriKind.Relative);
            
            #line 1 "..\..\..\UI\TextToCADTaskpaneWpf.xaml"
            System.Windows.Application.LoadComponent(this, resourceLocater);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
        void System.Windows.Markup.IComponentConnector.Connect(int connectionId, object target) {
            switch (connectionId)
            {
            case 1:
            this.presetLabel = ((System.Windows.Controls.Label)(target));
            return;
            case 2:
            this.shapePreset = ((System.Windows.Controls.ComboBox)(target));
            return;
            case 3:
            this.lblVersion = ((System.Windows.Controls.Label)(target));
            return;
            case 4:
            this.lblModified = ((System.Windows.Controls.Label)(target));
            return;
            case 5:
            this.prompt = ((System.Windows.Controls.TextBox)(target));
            return;
            case 6:
            this.build = ((System.Windows.Controls.Button)(target));
            return;
            case 7:
            this.lblRealTimeStatus = ((System.Windows.Controls.Label)(target));
            return;
            case 8:
            this.btnThumbUp = ((System.Windows.Controls.Button)(target));
            return;
            case 9:
            this.btnThumbDown = ((System.Windows.Controls.Button)(target));
            return;
            case 10:
            this.btnHistory = ((System.Windows.Controls.Button)(target));
            return;
            case 11:
            this.btnStatus = ((System.Windows.Controls.Button)(target));
            return;
            case 12:
            this.btnSettings = ((System.Windows.Controls.Button)(target));
            return;
            }
            this._contentLoaded = true;
        }
    }
}

