#pragma checksum "..\..\..\..\UI\TextToCADTaskpaneWpf.xaml" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "57FF75859D5D3CD0E1146B320A4FCE75021D924C"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Diagnostics;
using System.Windows;
using System.Windows.Automation;
using System.Windows.Controls;
using System.Windows.Controls.Primitives;
using System.Windows.Controls.Ribbon;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Forms.Integration;
using System.Windows.Ink;
using System.Windows.Input;
using System.Windows.Markup;
using System.Windows.Media;
using System.Windows.Media.Animation;
using System.Windows.Media.Effects;
using System.Windows.Media.Imaging;
using System.Windows.Media.Media3D;
using System.Windows.Media.TextFormatting;
using System.Windows.Navigation;
using System.Windows.Shapes;
using System.Windows.Shell;


namespace AICAD.UI {
    
    
    /// <summary>
    /// TextToCADTaskpaneWpf
    /// </summary>
    public partial class TextToCADTaskpaneWpf : System.Windows.Controls.UserControl, System.Windows.Markup.IComponentConnector {
        
        
        #line 23 "..\..\..\..\UI\TextToCADTaskpaneWpf.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button addSeriesButton;
        
        #line default
        #line hidden
        
        
        #line 34 "..\..\..\..\UI\TextToCADTaskpaneWpf.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label nextSequenceLabel;
        
        #line default
        #line hidden
        
        
        #line 36 "..\..\..\..\UI\TextToCADTaskpaneWpf.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ComboBox seriesComboBox;
        
        #line default
        #line hidden
        
        
        #line 48 "..\..\..\..\UI\TextToCADTaskpaneWpf.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ComboBox materialComboBox;
        
        #line default
        #line hidden
        
        
        #line 60 "..\..\..\..\UI\TextToCADTaskpaneWpf.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox typeDescriptionTextBox;
        
        #line default
        #line hidden
        
        
        #line 68 "..\..\..\..\UI\TextToCADTaskpaneWpf.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox weightTextBox;
        
        #line default
        #line hidden
        
        
        #line 75 "..\..\..\..\UI\TextToCADTaskpaneWpf.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox previewTextBox;
        
        #line default
        #line hidden
        
        
        #line 80 "..\..\..\..\UI\TextToCADTaskpaneWpf.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button saveWithNameButton;
        
        #line default
        #line hidden
        
        
        #line 85 "..\..\..\..\UI\TextToCADTaskpaneWpf.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button applyPropertiesButton;
        
        #line default
        #line hidden
        
        
        #line 93 "..\..\..\..\UI\TextToCADTaskpaneWpf.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label lblRealTimeStatus;
        
        #line default
        #line hidden
        
        
        #line 98 "..\..\..\..\UI\TextToCADTaskpaneWpf.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox prompt;
        
        #line default
        #line hidden
        
        
        #line 103 "..\..\..\..\UI\TextToCADTaskpaneWpf.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button build;
        
        #line default
        #line hidden
        
        
        #line 115 "..\..\..\..\UI\TextToCADTaskpaneWpf.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label presetLabel;
        
        #line default
        #line hidden
        
        
        #line 116 "..\..\..\..\UI\TextToCADTaskpaneWpf.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ComboBox shapePreset;
        
        #line default
        #line hidden
        
        
        #line 121 "..\..\..\..\UI\TextToCADTaskpaneWpf.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label lblVersion;
        
        #line default
        #line hidden
        
        
        #line 131 "..\..\..\..\UI\TextToCADTaskpaneWpf.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button btnThumbDown;
        
        #line default
        #line hidden
        
        
        #line 132 "..\..\..\..\UI\TextToCADTaskpaneWpf.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button btnThumbUp;
        
        #line default
        #line hidden
        
        
        #line 135 "..\..\..\..\UI\TextToCADTaskpaneWpf.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button btnHistory;
        
        #line default
        #line hidden
        
        
        #line 136 "..\..\..\..\UI\TextToCADTaskpaneWpf.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button btnSettings;
        
        #line default
        #line hidden
        
        private bool _contentLoaded;
        
        /// <summary>
        /// InitializeComponent
        /// </summary>
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "9.0.11.0")]
        public void InitializeComponent() {
            if (_contentLoaded) {
                return;
            }
            _contentLoaded = true;
            System.Uri resourceLocater = new System.Uri("/AI-CAD-December;V1.0.0.0;component/ui/texttocadtaskpanewpf.xaml", System.UriKind.Relative);
            
            #line 1 "..\..\..\..\UI\TextToCADTaskpaneWpf.xaml"
            System.Windows.Application.LoadComponent(this, resourceLocater);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "9.0.11.0")]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
        void System.Windows.Markup.IComponentConnector.Connect(int connectionId, object target) {
            switch (connectionId)
            {
            case 1:
            this.addSeriesButton = ((System.Windows.Controls.Button)(target));
            return;
            case 2:
            this.nextSequenceLabel = ((System.Windows.Controls.Label)(target));
            return;
            case 3:
            this.seriesComboBox = ((System.Windows.Controls.ComboBox)(target));
            return;
            case 4:
            this.materialComboBox = ((System.Windows.Controls.ComboBox)(target));
            return;
            case 5:
            this.typeDescriptionTextBox = ((System.Windows.Controls.TextBox)(target));
            return;
            case 6:
            this.weightTextBox = ((System.Windows.Controls.TextBox)(target));
            return;
            case 7:
            this.previewTextBox = ((System.Windows.Controls.TextBox)(target));
            return;
            case 8:
            this.saveWithNameButton = ((System.Windows.Controls.Button)(target));
            return;
            case 9:
            this.applyPropertiesButton = ((System.Windows.Controls.Button)(target));
            return;
            case 10:
            this.lblRealTimeStatus = ((System.Windows.Controls.Label)(target));
            return;
            case 11:
            this.prompt = ((System.Windows.Controls.TextBox)(target));
            return;
            case 12:
            this.build = ((System.Windows.Controls.Button)(target));
            return;
            case 13:
            this.presetLabel = ((System.Windows.Controls.Label)(target));
            return;
            case 14:
            this.shapePreset = ((System.Windows.Controls.ComboBox)(target));
            return;
            case 15:
            this.lblVersion = ((System.Windows.Controls.Label)(target));
            return;
            case 16:
            this.btnThumbDown = ((System.Windows.Controls.Button)(target));
            return;
            case 17:
            this.btnThumbUp = ((System.Windows.Controls.Button)(target));
            return;
            case 18:
            this.btnHistory = ((System.Windows.Controls.Button)(target));
            return;
            case 19:
            this.btnSettings = ((System.Windows.Controls.Button)(target));
            return;
            }
            this._contentLoaded = true;
        }
    }
}

