#pragma checksum "..\..\..\..\UI\TextToCADTaskpaneWpf.xaml" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "8C986CD489FFEE98A42B141B5F351D5E5F2AE09D"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Diagnostics;
using System.Windows;
using System.Windows.Automation;
using System.Windows.Controls;
using System.Windows.Controls.Primitives;
using System.Windows.Controls.Ribbon;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Forms.Integration;
using System.Windows.Ink;
using System.Windows.Input;
using System.Windows.Markup;
using System.Windows.Media;
using System.Windows.Media.Animation;
using System.Windows.Media.Effects;
using System.Windows.Media.Imaging;
using System.Windows.Media.Media3D;
using System.Windows.Media.TextFormatting;
using System.Windows.Navigation;
using System.Windows.Shapes;
using System.Windows.Shell;


namespace AICAD.UI {
    
    
    /// <summary>
    /// TextToCADTaskpaneWpf
    /// </summary>
    public partial class TextToCADTaskpaneWpf : System.Windows.Controls.UserControl, System.Windows.Markup.IComponentConnector {
        
        
        #line 24 "..\..\..\..\UI\TextToCADTaskpaneWpf.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button addSeriesButton;
        
        #line default
        #line hidden
        
        
        #line 31 "..\..\..\..\UI\TextToCADTaskpaneWpf.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.StackPanel KaraokeLinesPanel;
        
        #line default
        #line hidden
        
        
        #line 35 "..\..\..\..\UI\TextToCADTaskpaneWpf.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label nextSequenceLabel;
        
        #line default
        #line hidden
        
        
        #line 37 "..\..\..\..\UI\TextToCADTaskpaneWpf.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ComboBox seriesComboBox;
        
        #line default
        #line hidden
        
        
        #line 49 "..\..\..\..\UI\TextToCADTaskpaneWpf.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ComboBox materialComboBox;
        
        #line default
        #line hidden
        
        
        #line 80 "..\..\..\..\UI\TextToCADTaskpaneWpf.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox typeDescriptionTextBox;
        
        #line default
        #line hidden
        
        
        #line 88 "..\..\..\..\UI\TextToCADTaskpaneWpf.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox weightTextBox;
        
        #line default
        #line hidden
        
        
        #line 95 "..\..\..\..\UI\TextToCADTaskpaneWpf.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox previewTextBox;
        
        #line default
        #line hidden
        
        
        #line 100 "..\..\..\..\UI\TextToCADTaskpaneWpf.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button saveWithNameButton;
        
        #line default
        #line hidden
        
        
        #line 105 "..\..\..\..\UI\TextToCADTaskpaneWpf.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button applyPropertiesButton;
        
        #line default
        #line hidden
        
        
        #line 126 "..\..\..\..\UI\TextToCADTaskpaneWpf.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.StackPanel ProgressStatusPanel;
        
        #line default
        #line hidden
        
        
        #line 128 "..\..\..\..\UI\TextToCADTaskpaneWpf.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock KaraokeStatus;
        
        #line default
        #line hidden
        
        
        #line 142 "..\..\..\..\UI\TextToCADTaskpaneWpf.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ProgressBar generationProgressBar;
        
        #line default
        #line hidden
        
        
        #line 144 "..\..\..\..\UI\TextToCADTaskpaneWpf.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock generationProgressText;
        
        #line default
        #line hidden
        
        
        #line 153 "..\..\..\..\UI\TextToCADTaskpaneWpf.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox prompt;
        
        #line default
        #line hidden
        
        
        #line 163 "..\..\..\..\UI\TextToCADTaskpaneWpf.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button build;
        
        #line default
        #line hidden
        
        
        #line 178 "..\..\..\..\UI\TextToCADTaskpaneWpf.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label presetLabel;
        
        #line default
        #line hidden
        
        
        #line 179 "..\..\..\..\UI\TextToCADTaskpaneWpf.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ComboBox shapePreset;
        
        #line default
        #line hidden
        
        
        #line 184 "..\..\..\..\UI\TextToCADTaskpaneWpf.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label lblVersion;
        
        #line default
        #line hidden
        
        
        #line 194 "..\..\..\..\UI\TextToCADTaskpaneWpf.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button btnThumbDown;
        
        #line default
        #line hidden
        
        
        #line 195 "..\..\..\..\UI\TextToCADTaskpaneWpf.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button btnThumbUp;
        
        #line default
        #line hidden
        
        
        #line 196 "..\..\..\..\UI\TextToCADTaskpaneWpf.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label feedbackLabel;
        
        #line default
        #line hidden
        
        
        #line 197 "..\..\..\..\UI\TextToCADTaskpaneWpf.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label feedbackSucessLabel;
        
        #line default
        #line hidden
        
        
        #line 201 "..\..\..\..\UI\TextToCADTaskpaneWpf.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button btnHistory;
        
        #line default
        #line hidden
        
        
        #line 202 "..\..\..\..\UI\TextToCADTaskpaneWpf.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button btnStatus;
        
        #line default
        #line hidden
        
        
        #line 203 "..\..\..\..\UI\TextToCADTaskpaneWpf.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button btnSettings;
        
        #line default
        #line hidden
        
        private bool _contentLoaded;
        
        /// <summary>
        /// InitializeComponent
        /// </summary>
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "9.0.11.0")]
        public void InitializeComponent() {
            if (_contentLoaded) {
                return;
            }
            _contentLoaded = true;
            System.Uri resourceLocater = new System.Uri("/AI-CAD-December;V1.0.0.0;component/ui/texttocadtaskpanewpf.xaml", System.UriKind.Relative);
            
            #line 1 "..\..\..\..\UI\TextToCADTaskpaneWpf.xaml"
            System.Windows.Application.LoadComponent(this, resourceLocater);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "9.0.11.0")]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
        void System.Windows.Markup.IComponentConnector.Connect(int connectionId, object target) {
            switch (connectionId)
            {
            case 1:
            this.addSeriesButton = ((System.Windows.Controls.Button)(target));
            return;
            case 2:
            this.KaraokeLinesPanel = ((System.Windows.Controls.StackPanel)(target));
            return;
            case 3:
            this.nextSequenceLabel = ((System.Windows.Controls.Label)(target));
            return;
            case 4:
            this.seriesComboBox = ((System.Windows.Controls.ComboBox)(target));
            return;
            case 5:
            this.materialComboBox = ((System.Windows.Controls.ComboBox)(target));
            return;
            case 6:
            this.typeDescriptionTextBox = ((System.Windows.Controls.TextBox)(target));
            return;
            case 7:
            this.weightTextBox = ((System.Windows.Controls.TextBox)(target));
            return;
            case 8:
            this.previewTextBox = ((System.Windows.Controls.TextBox)(target));
            return;
            case 9:
            this.saveWithNameButton = ((System.Windows.Controls.Button)(target));
            return;
            case 10:
            this.applyPropertiesButton = ((System.Windows.Controls.Button)(target));
            return;
            case 11:
            this.ProgressStatusPanel = ((System.Windows.Controls.StackPanel)(target));
            return;
            case 12:
            this.KaraokeStatus = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 13:
            this.generationProgressBar = ((System.Windows.Controls.ProgressBar)(target));
            return;
            case 14:
            this.generationProgressText = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 15:
            this.prompt = ((System.Windows.Controls.TextBox)(target));
            
            #line 158 "..\..\..\..\UI\TextToCADTaskpaneWpf.xaml"
            this.prompt.GotFocus += new System.Windows.RoutedEventHandler(this.prompt_GotFocus);
            
            #line default
            #line hidden
            
            #line 159 "..\..\..\..\UI\TextToCADTaskpaneWpf.xaml"
            this.prompt.LostFocus += new System.Windows.RoutedEventHandler(this.prompt_LostFocus);
            
            #line default
            #line hidden
            
            #line 160 "..\..\..\..\UI\TextToCADTaskpaneWpf.xaml"
            this.prompt.PreviewKeyDown += new System.Windows.Input.KeyEventHandler(this.prompt_PreviewKeyDown);
            
            #line default
            #line hidden
            return;
            case 16:
            this.build = ((System.Windows.Controls.Button)(target));
            return;
            case 17:
            this.presetLabel = ((System.Windows.Controls.Label)(target));
            return;
            case 18:
            this.shapePreset = ((System.Windows.Controls.ComboBox)(target));
            return;
            case 19:
            this.lblVersion = ((System.Windows.Controls.Label)(target));
            return;
            case 20:
            this.btnThumbDown = ((System.Windows.Controls.Button)(target));
            return;
            case 21:
            this.btnThumbUp = ((System.Windows.Controls.Button)(target));
            return;
            case 22:
            this.feedbackLabel = ((System.Windows.Controls.Label)(target));
            return;
            case 23:
            this.feedbackSucessLabel = ((System.Windows.Controls.Label)(target));
            return;
            case 24:
            this.btnHistory = ((System.Windows.Controls.Button)(target));
            return;
            case 25:
            this.btnStatus = ((System.Windows.Controls.Button)(target));
            return;
            case 26:
            this.btnSettings = ((System.Windows.Controls.Button)(target));
            return;
            }
            this._contentLoaded = true;
        }
    }
}

